### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by lennartkoopmann** [lennartkoopmann/nzyme#166]
```
11:53:00.925 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11Probe - Could not process packet.
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_212]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_212]
	at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:325) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at com.google.common.collect.ImmutableMap$Builder.putAll(ImmutableMap.java:309) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.networks.Networks.getBSSIDs(Networks.java:261) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.networks.Networks.getSignalDelta(Networks.java:284) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.handlers.Dot11FrameHandler.buildDeltaInformationFields(Dot11FrameHandler.java:59) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.handlers.Dot11ProbeResponseFrameHandler.doHandle(Dot11ProbeResponseFrameHandler.java:46) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.handlers.Dot11ProbeResponseFrameHandler.doHandle(Dot11ProbeResponseFrameHandler.java:29) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.handlers.Dot11FrameHandler.handle(Dot11FrameHandler.java:48) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe$4.intercept(Dot11MonitorProbe.java:355) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe$4.intercept(Dot11MonitorProbe.java:350) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:226) ~[nzyme-1.0.0-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by lennartkoopmann** [comment]
This has been resolved during a re-architecture and I have not seen any `ConcurrentModificationException` since then.
