### ISSUE TITLE
MalformedFrameException

### ISSUE THREAD

**Issue by lennartkoopmann** [lennartkoopmann/nzyme#242]
```
13:40:04.986 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11Probe - Skipping malformed frame.
horse.wtf.nzyme.dot11.MalformedFrameException: Could not parse 802.11 tagged parameters.
	at horse.wtf.nzyme.dot11.Dot11TaggedParameters.<init>(Dot11TaggedParameters.java:117) ~[classes/:?]
	at horse.wtf.nzyme.dot11.parsers.Dot11BeaconFrameParser.doParse(Dot11BeaconFrameParser.java:35) ~[classes/:?]
	at horse.wtf.nzyme.dot11.parsers.Dot11BeaconFrameParser.doParse(Dot11BeaconFrameParser.java:26) ~[classes/:?]
	at horse.wtf.nzyme.dot11.parsers.Dot11FrameParser.parse(Dot11FrameParser.java:47) ~[classes/:?]
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:229) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 93
	at horse.wtf.nzyme.dot11.Dot11TaggedParameters.<init>(Dot11TaggedParameters.java:84) ~[classes/:?]
	... 9 more
```

**Comment by joramk** [comment]
`18:54:17.896 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11Probe - Skipping malformed frame on probe [broad-monitor-wlanExt].
horse.wtf.nzyme.dot11.MalformedFrameException: Could not parse 802.11 tagged parameters.
        at horse.wtf.nzyme.dot11.Dot11TaggedParameters.<init>(Dot11TaggedParameters.java:123) ~[nzyme-1.0.0.jar:?]
        at horse.wtf.nzyme.dot11.parsers.Dot11BeaconFrameParser.doParse(Dot11BeaconFrameParser.java:40) ~[nzyme-1.0.0.jar:?]
        at horse.wtf.nzyme.dot11.parsers.Dot11BeaconFrameParser.doParse(Dot11BeaconFrameParser.java:27) ~[nzyme-1.0.0.jar:?]
        at horse.wtf.nzyme.dot11.parsers.Dot11FrameParser.parse(Dot11FrameParser.java:47) ~[nzyme-1.0.0.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:240) ~[nzyme-1.0.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: arr.length: 249, offset: 247, len: 101, arr: 80000000fffffffffffff4068d8dd6d9f4068d8dd6d9e03d8031298e090000006400110400136465766f6c6f2d333064333264353935356462010882848b960c12182403010b0504000100002a010432043048606c2d1a6e1103ff000000000000000000000000000000000000000000003d160b0804000000000000000000000000000000000000004a0e14000a002c01c8001400050019007f050100000000dd180050f2020101000003a4000027a4000042435e0062322f00dd0900037f01010000ff7f30140100000fac040100000fac040100000fac020000dd180050f204104a00011010440001021049000600372a000120f765bb62
        at org.pcap4j.util.ByteArrays.validateBounds(ByteArrays.java:973) ~[nzyme-1.0.0.jar:?]
        at org.pcap4j.util.ByteArrays.getSubArray(ByteArrays.java:738) ~[nzyme-1.0.0.jar:?]
        at horse.wtf.nzyme.dot11.Dot11TaggedParameters.<init>(Dot11TaggedParameters.java:95) ~[nzyme-1.0.0.jar:?]
        ... 9 more`
This error gets logged every 2 milliseconds.  As a workaround I disabled the logging in log4j2-debian.xml
`<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
    <Appenders>
        <RollingFile name="Logfile" fileName="/var/log/nzyme/nzyme.log" filePattern="logs/$${date:yyyy-MM}/nzyme-%d{yyyy-MM-dd}-%i.log.gz">
            <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n" />
            <Policies>
                <TimeBasedTriggeringPolicy />
                <SizeBasedTriggeringPolicy size="100 MB"/>
            </Policies>
            <DefaultRolloverStrategy max="20"/>
        </RollingFile>
    </Appenders>
    <Loggers>
        <Root level="off">
            <AppenderRef ref="Logfile" />
        </Root>

        <Logger name="org.pcap4j" level="off">
            <AppenderRef ref="Logfile" />
        </Logger>

        <Logger name="liquibase" level="off">
            <AppenderRef ref="Logfile" />
        </Logger>

        <Logger name="org.glassfish.grizzly" level="off">
            <AppenderRef ref="Logfile" />
        </Logger>
    </Loggers>
</Configuration>`

**Comment by mathieubrun** [comment]
Had the same issue here, I fixed it by adding additional check in Dot11TaggedParameters. Now I'm getting a lot more frames in the 802.11 Frame Throughput graph.

**Comment by mathieubrun** [comment]
Did a bit of investigation using wireshark, the 2nd byte after the last know valid tag can indicate a wrong length and as such throw the array out of bounds exception.

**Comment by lennartkoopmann** [comment]
Thank you! I'll take a look ASAP and moved this issue up to the next closest milestone.

**Comment by lennartkoopmann** [comment]
This will be entirely rewritten in v2.0.0
