### ISSUE TITLE
gelf tcp transport error

### ISSUE THREAD

**Issue by mbj047** [lennartkoopmann/nzyme#286]
Hi,
Great project. I realize this branch is old and likely dead but in waiting for branch v1 I am trying to get v0.2.1 working on a pi 4. Everything seems to be working fine on collection but export to graylog doesn't seem to be working and its returning -
```
15:16:22.329 [gelfTcpTransport-1-1] ERROR org.graylog2.gelfclient.transport.GelfTcpTransport - Exception caught
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_212]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_212]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_212]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_212]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_212]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) ~[nzyme-0.2.1.jar:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[nzyme-0.2.1.jar:?]
        at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:641) ~[nzyme-0.2.1.jar:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) ~[nzyme-0.2.1.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [nzyme-0.2.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [nzyme-0.2.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [nzyme-0.2.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [nzyme-0.2.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [nzyme-0.2.1.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [nzyme-0.2.1.jar:?]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [nzyme-0.2.1.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
15:16:22.358 [gelfTcpTransport-1-1] ERROR org.graylog2.gelfclient.encoder.GelfMessageJsonEncoder - JSON encoding error
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_212]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_212]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_212]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_212]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_212]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) ~[nzyme-0.2.1.jar:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[nzyme-0.2.1.jar:?]
        at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:641) ~[nzyme-0.2.1.jar:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) ~[nzyme-0.2.1.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [nzyme-0.2.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [nzyme-0.2.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [nzyme-0.2.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [nzyme-0.2.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [nzyme-0.2.1.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [nzyme-0.2.1.jar:?]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [nzyme-0.2.1.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
15:16:22.364 [gelfTcpTransport-1-1] INFO  org.graylog2.gelfclient.transport.GelfTcpTransport - Channel disconnected!
``` 

openjdk version "1.8.0_212"
Graylog gelftcp is listening on port 5555

Any suggestions? 

Thanks

**Comment by mbj047** [comment]
I changed the port and turned on tcp keep alive which cleared up the error in nzyme log but graylog is failed to process with - 
```
2020-09-05T11:09:02.868-04:00 ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=669eb810-ef88-11ea-8389-1644e80aace3, journalOffset=4, codec=CEF, payloadSize=1281668, timestamp=2020-09-05T14:59:30.449Z, remoteAddress=/10.10.50.99:42360} on input <5f5268156e0c0207c634403a>.
2020-09-05T11:09:02.870-04:00 ERROR [DecodingProcessor] Error processing message RawMessage{id=669eb810-ef88-11ea-8389-1644e80aace3, journalOffset=4, codec=CEF, payloadSize=1281668, timestamp=2020-09-05T14:59:30.449Z, remoteAddress=/10.10.50.99:42360}
java.lang.NullPointerException: null
        at org.graylog.plugins.cef.parser.MappedMessage.<init>(MappedMessage.java:37) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decodeCEF(CEFCodec.java:128) ~[graylog.jar:?]
        at org.graylog.plugins.cef.codec.CEFCodec.decode(CEFCodec.java:117) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:150) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:90) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:47) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

**Comment by lennartkoopmann** [comment]
Hi Jason,

thank you! I think there is a mix-up with input types happening here. You say that you are sending the nzyme messages into a GELF TCP input in Graylog, but the stack trace shows errors coming out of the CEF input.

Could you double check that the messages are going into a GELF TCP input? Is there any port-forwarding somewhere happening on the way? Maybe ports get switched up during that.

**Comment by mbj047** [comment]
I apologize! I did have the input wrong in Graylog. For some reason I was convinced the issue was on the sending side. Works great. Thank you.

**Comment by lennartkoopmann** [comment]
Great! Thank you.
