### ISSUE TITLE
ConcurrentModificationException in new FrameProcessor

### ISSUE THREAD

**Issue by lennartkoopmann** [lennartkoopmann/nzyme#374]
```
13:51:45.999 [remote-input-0] WARN  horse.wtf.nzyme.remote.inputs.RemoteFrameInput - Error receiving remote frame. Skipping.
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
	at horse.wtf.nzyme.processing.FrameProcessor.processDot11Frame(FrameProcessor.java:55) ~[classes/:?]
	at horse.wtf.nzyme.remote.inputs.RemoteFrameInput.lambda$run$0(RemoteFrameInput.java:121) ~[classes/:?]
```

**Comment by lennartkoopmann** [comment]
Fixed in db1f94d7ed2ef22526fef17d66c26ab16561c4ac
