### ISSUE TITLE
Which driver for ALFA AWUS036ACH on Raspi 4B

### ISSUE THREAD

**Issue by MarpleA** [lennartkoopmann/nzyme#376]
I installed the rtl8812 driver version 5.6.4.2 from https://github.com/aircrack-ng/rtl8812au
The driver installation does work fine and I am able to put the interface into monitoring mode, however nzyme throws this error:

`01:19:32.088 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11Probe - Building PCAP handle on interface [wlx00c0caa513d9]
01:19:32.127 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11Probe - Could not initialize probe [broad-monitor-wlx00c0caa513d9]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:149) ~[nzyme-1.0.0.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:163) ~[nzyme-1.0.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: wlx00c0caa513d9: SIOCGIWPRIV: Argument list too long
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-1.0.0.jar:?]
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:45) ~[nzyme-1.0.0.jar:?]
        at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1529) ~[nzyme-1.0.0.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:143) ~[nzyme-1.0.0.jar:?]
        ... 6 more
`

This error message was mentioned before and solve by using version 5.1.5 of the aircrack-ng driver. But for Raspberry Pi 4B this driver and basically every driver below 5.6.4.2 is not compatible / compileable.

Any ideas if there's a fork of this driver which works or even better if there is a solution in nzyme to get it going?

EDIT: after some reading, I assume that's an issue with kernel 5.10x but I haven't found a solution yet.

**Comment by lennartkoopmann** [comment]
I was not able to get the AWUS036ACH to work yet and I'm not aware of any driver that works with it.

I recommend using one of the tested and supported adapters from here: https://www.nzyme.org/documentation/requirements
