### ISSUE TITLE
Can't run after installation - debian9

### ISSUE THREAD

**Issue by nemapl** [lennartkoopmann/nzyme#421]
Hello,
 I've tried on multiple systems and can't run nzyme.
What I can see in log file (tail -f /var/log/nzyme/nzyme.log):
`21:45:40.819 [main] ERROR horse.wtf.nzyme.Main - Invalid configuration. Please refer to the example configuration file or documentation.
horse.wtf.nzyme.configuration.InvalidConfigurationException: Parameter [general.python.path] does not point to an executable file: /usr/bin/python3.8
	at horse.wtf.nzyme.configuration.leader.LeaderConfigurationLoader.validate(LeaderConfigurationLoader.java:448) ~[nzyme-1.1.0.jar:?]
	at horse.wtf.nzyme.configuration.leader.LeaderConfigurationLoader.<init>(LeaderConfigurationLoader.java:78) ~[nzyme-1.1.0.jar:?]
	at horse.wtf.nzyme.Main.main(Main.java:84) [nzyme-1.1.0.jar:?]
`

I've found that it was about python path - changing to /usr/bin/python3.5 solved initial point.

Now what I can see in the log file is:
`probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - org.pcap4j.core.PcapNativeException: Error occurred in pcap_next_ex(): The interface went down
22:32:11.176 [channel-hopper-0] FATAL horse.wtf.nzyme.channels.ChannelHopper - Could not configure interface [wlo1] to use channel <6>. Return code <250>, STDERR: [Error for wireless request "Set Frequency" (8B04) :    SET failed on device wlo1 ; Device or resource busy.]
22:32:11.586 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlo1]
22:32:11.675 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlo1]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.1.0.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: That device doesn't support monitor mode
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-1.1.0.jar:?]
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:45) ~[nzyme-1.1.0.jar:?]
        at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1529) ~[nzyme-1.1.0.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:116) ~[nzyme-1.1.0.jar:?]
        ... 6 more
`

And it is disaplyed in red
![image](https://user-images.githubusercontent.com/1636088/116149164-192aff00-a6e2-11eb-8cae-91f6e4937042.png)

**Comment by lennartkoopmann** [comment]
The `Device or resource busy` message indicates that something else is accessing that interface. Is it possible that you have other things running that use the interface? On Linux that could be `NetworkManager` or `wpa_supplicant`.

What does `iwconfig` show?

**Comment by nemapl** [comment]
Yes, you are right - it was network manager - after switching off -> everything on green :)
BTW: is it possible to have nzyme running and in the same time have station connected to wifi? Or rather run it over eth and use wifi only for monitor?

**Comment by nemapl** [comment]
I can see following entries:
```
19:07:03.972 [main] ERROR horse.wtf.nzyme.NzymeLeaderImpl - Could not initialize OUIs.
java.net.UnknownHostException: standards-oui.ieee.org: Ta nazwa lub usługa jest nieznana (This name or service is unknown)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[?:?]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515) ~[?:?]
        at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) ~[?:?]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1364) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1298) ~[?:?]
        at okhttp3.Dns$Companion$SYSTEM$1.lookup(Dns.kt:48) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:160) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:125) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[nzyme-1.1.0.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184) ~[nzyme-1.1.0.jar:?]
        at okhttp3.RealCall.execute(RealCall.kt:66) ~[nzyme-1.1.0.jar:?]
        at horse.wtf.nzyme.ouis.OUIManager.fetchAndUpdate(OUIManager.java:101) ~[nzyme-1.1.0.jar:?]
        at horse.wtf.nzyme.NzymeLeaderImpl.initialize(NzymeLeaderImpl.java:205) [nzyme-1.1.0.jar:?]
        at horse.wtf.nzyme.Main.main(Main.java:109) [nzyme-1.1.0.jar:?]19:07:04.131 [periodicals-2] ERROR 19:07:04.131 [periodicals-2] ERROR horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread - Could not check for newest nzyme version. Please consult the README.
java.net.UnknownHostException: versionchecks.nzyme.org: Ta nazwa lub usługa jest nieznana
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929) ~[?:?]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515) ~[?:?]
        at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848) ~[?:?]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1505) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1364) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1298) ~[?:?]
        at okhttp3.Dns$Companion$SYSTEM$1.lookup(Dns.kt:48) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:160) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:125) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112) ~[nzyme-1.1.0.jar:?]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87) ~[nzyme-1.1.0.jar:?]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184) ~[nzyme-1.1.0.jar:?]
        at okhttp3.RealCall.execute(RealCall.kt:66) ~[nzyme-1.1.0.jar:?]
        at horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread.execute(VersioncheckThread.java:81) [nzyme-1.1.0.jar:?]
        at horse.wtf.nzyme.periodicals.Periodical.run(Periodical.java:39) [nzyme-1.1.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by nemapl** [comment]
I'e switched to 2nd machine where is eth0 and wifi interface.
I've stopped network-manager and wpa - now in the log files I can see:
```
21:00:10.821 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlo1]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not get network interface [wlo1]. Does it exist and could it be that you have to be root? Is it up?
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:102) ~[nzyme-1.1.0.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Comment by andrewbeard** [comment]
> I can see following entries:

Sounds like both of those errors are related to nzyme not having an internet connection. I know you can disable the OUI download via a config entry. I'm less sure about the new version check but if you can't it seems like a reasonable thing to do.

**Comment by lennartkoopmann** [comment]
It looks like `NetworkManager` and `rfkill` are interfering with your WiFi adpters again. Did you disable them after switching to the new server?
