### ISSUE TITLE
Trap: BEACON_1 throws "Module not found scapy"

### ISSUE THREAD

**Issue by MarpleA** [lennartkoopmann/nzyme#430]
setting up traps following the documentation leads to following error message:

`19:42:00.101 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - Bluff [horse.wtf.nzyme.dot11.deception.bluffs.Beacon]: Invoked command {/usr/bin/python3.7 /tmp/nzyme_Beacon --interface wlx9cefd4fbdbc7 --ssid test_Management --mac B4:FB:E4:CB:D4:7F}.
19:42:00.101 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff - Bluff [horse.wtf.nzyme.dot11.deception.bluffs.Beacon]: 4 lines written to STDERR:
19:42:00.102 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff -                STDERR: Traceback (most recent call last):
19:42:00.102 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff -                STDERR:   File "/tmp/nzyme_Beacon", line 4, in <module>
19:42:00.103 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff -                STDERR:     from scapy.all import *
19:42:00.103 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.deception.bluffs.Bluff -                STDERR: ModuleNotFoundError: No module named 'scapy'
19:42:00.103 [probe-loop-1] ERROR horse.wtf.nzyme.dot11.deception.traps.BeaconTrap - Could not set Beacon for SSID [test_Management].
horse.wtf.nzyme.dot11.deception.bluffs.Bluff$BluffExecutionException: STDERR is not empty.
        at horse.wtf.nzyme.dot11.deception.bluffs.Bluff.execute(Bluff.java:99) ~[nzyme-1.1.0.jar:?]
        at horse.wtf.nzyme.dot11.deception.traps.BeaconTrap.doRun(BeaconTrap.java:88) ~[nzyme-1.1.0.jar:?]
        at horse.wtf.nzyme.dot11.deception.traps.Trap.run(Trap.java:75) ~[nzyme-1.1.0.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11SenderProbe.lambda$loop$0(Dot11SenderProbe.java:118) ~[nzyme-1.1.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
`

**Comment by MarpleA** [comment]
for the record.
on raspberry one can simply install scapy by 
`apt install python3-scapy`

**Comment by lennartkoopmann** [comment]
Did this solve your issue? Please close this issue if it did. Thanks!
