### ISSUE TITLE
Error running jar

### ISSUE THREAD

**Issue by malled** [lennartkoopmann/nzyme#44]
Hello,

I would like to extend nzyme to capture more package information. Therefore I built a jar-file with `mvn package` and executed it (without modifying any code). Unfortunately, when executing the jar, I cannot connect to my graylog instance (error message below).

Running the deb package works fine though. 
You know what's wrong?

```

10:51:06.888 [gelfTcpTransport-1-1] INFO  org.graylog2.gelfclient.transport.GelfTcpTransport - Channel disconnected!
10:51:07.948 [gelfTcpTransport-1-1] ERROR org.graylog2.gelfclient.transport.GelfTcpTransport - Exception caught
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_171]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_171]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_171]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_171]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) ~[nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) ~[nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [nzyme-0.2-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
10:51:07.960 [gelfTcpTransport-1-1] ERROR org.graylog2.gelfclient.encoder.GelfMessageJsonEncoder - JSON encoding error
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_171]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_171]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_171]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_171]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_171]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) ~[nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) ~[nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [nzyme-0.2-SNAPSHOT.jar:?]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [nzyme-0.2-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

```

**Comment by lennartkoopmann** [comment]
> java.io.IOException: Connection reset by peer

This looks like a network connectivity issue to Graylog. Please check your configuration and make sure that nzyme can connect to your Graylog GELF input.

**Comment by malled** [comment]
@lennartkoopmann thanks, I've accidentially tried to connect to the web url. It's working now.

**Comment by RichardPhilipsRoy** [comment]
@malled Hi i'm having the same problem which url should i use in graylog address web url or REST API url, i tried both of them still same ERROR.

**Comment by malled** [comment]
@RichardPhilipsRoy you have to create a new input and use the address/port specified there. See http://docs.graylog.org/en/2.4/pages/getting_started/collect.html#create-an-input

**Comment by RichardPhilipsRoy** [comment]
Thank you
