### ISSUE TITLE
Nzyme dashbord stoped working with: REST call failed. (HTTP 500)

### ISSUE THREAD

**Issue by gatekeeper8** [lennartkoopmann/nzyme#473]
[grizzly-http-server-5] ERROR horse.wtf.nzyme.rest.NzymeExceptionMapper - Error while handling REST call.
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [nzyme-1.1.0.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [nzyme-1.1.0.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [nzyme-1.1.0.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [nzyme-1.1.0.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [nzyme-1.1.0.jar:?]
Unfurtunatelly I've not other logs, they rotated.

**Comment by lennartkoopmann** [comment]
Assuming this is the same as #472

**Comment by lennartkoopmann** [comment]
This was fixed in #472 and released with v1.1.1
