### ISSUE TITLE
ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe

### ISSUE THREAD

**Issue by hktalent** [lennartkoopmann/nzyme#506]
$ sudo java -jar nzyme-1.1.1.jar -c nzyme.conf

```
ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlx00c0ca971201]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not get network interface [wlx00c0ca971201]. Does it exist and could it be that you have to be root? Is it up?
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:102) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```
Mac OS no setcap
so,
sudo setcap cap_net_raw,cap_net_admin=eip  java -jar nzyme-1.1.1.jar -c nzyme.conf
can not run

**Comment by lennartkoopmann** [comment]
`setcap` should not be related to this problem. Can you confirm that you have a local WiFi interface called `wlx00c0ca971201` and that it is up?

**Comment by hktalent** [comment]
> `setcap` should not be related to this problem. Can you confirm that you have a local WiFi interface called `wlx00c0ca971201` and that it is up?

yes, all wifi interface is up
macOS not command setcap

**Comment by lennartkoopmann** [comment]
Can you show the output that shows that all interfaces are up? This is usually a pretty clear case.

**Comment by hktalent** [comment]
> Can you show the output that shows that all interfaces are up? This is usually a pretty clear case.
@lennartkoopmann  
```
51pwn@51pwns-MacBook-Pro Downloads $ sudo java -jar nzyme-1.1.1.jar -c nzyme.conf
sudo java -jar nzyme-1.1.1.jar -c nzyme.conf
Password:
12:29:46.486 [main] INFO  horse.wtf.nzyme.configuration.leader.LeaderConfigurationLoader - Skipping disabled alert callback of type [email].
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" org.jdbi.v3.core.ConnectionException: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:319)
	at horse.wtf.nzyme.database.Database.initializeAndMigrate(Database.java:66)
	at horse.wtf.nzyme.Main.main(Main.java:99)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.connect(Driver.java:264)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.jdbi.v3.core.Jdbi.lambda$create$0(Jdbi.java:114)
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:303)
	... 2 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
	at org.postgresql.core.PGStream.<init>(PGStream.java:95)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	... 10 more
51pwn@51pwns-MacBook-Pro Downloads $ ls nzyme.conf
nzyme.conf
nzyme.conf
51pwn@51pwns-MacBook-Pro Downloads $ ifconfig en0

en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 90:9c:4a:ce:39:72 
	inet6 fe80::74:7bd3:a01c:7369%en0 prefixlen 64 secured scopeid 0x6 
	inet 172.20.10.2 netmask 0xfffffff0 broadcast 172.20.10.15
	inet6 240e:476:b801:164f:89d:7885:375c:cf3b prefixlen 64 autoconf secured 
	inet6 240e:476:b801:164f:dd9a:b211:957f:3c98 prefixlen 64 autoconf temporary 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
51pwn@51pwns-MacBook-Pro Downloads $ sudo setcap cap_net_raw,cap_net_admin=eip java -jar nzyme-1.1.1.jar -c nzyme.conf
sudo setcap cap_net_raw,cap_net_admin=eip java -jar nzyme-1.1.1.jar -c nzyme.conf
sudo: setcap: command not found
```
