### ISSUE TITLE
Many Alerts

### ISSUE THREAD

**Issue by crs369** [lennartkoopmann/nzyme#510]
Hello,

this is my first post to the nzyme community. Thanks for the great tool.

First my Environment:
I'm using two Ubiquiti nanoHD access points, that both configured with two ssid myipng and myipng_guest
and a Raspberry Pi 4 with 8 GB and a WLAN USB-Adapter Edimax EW-7612UAN V2

Baseimage is the actual rasbian - lite.

I encounter al lot of Alerts like that:
```
SSID [myipng_guest] was advertised by a device with unexpected fingerprint [2471dd330f328c582f71c3142802b2a84fd1cb87183f5be9cff4574ee7bbe66a]
SSID [myipng_guest] was advertised with a probe response by a device with unexpected fingerprint [ee59554b8e115cbe3b0c74a0de27e81ec601ba7b250e257fb6a28ab0ed8a1f05]
```

I gave up after adding 17 fingeprints in the nzyme.conf

I got also also lot of Alerts of that type:

```
SSID [myipng] was advertised with unexpected security settings [].

Our BSSID [fe:ec:da:1f:f1:12] advertised unexpected SSID [+] with beacon frame.
Our BSSID [fc:ec:da:4f:81:00] advertised unexpected SSID [Z] with beacon frame.
Our BSSID [fe:ec:da:1f:81:00] advertised unexpected SSID [0] with beacon frame.
```

In nzyme.log i see messages with "Malformed 802.11 tagged parameters".

Any tipps für me to get rid of this alerts?

nzymne.log:
```
17:05:20.575 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff 8a 5c 44 85 0a 7c 8a 5c 44 85 0a 7c d0 65 32 e4 0a b3 12 00 00 00 64 00 21 04 00 11 56 6f 64 61 66 6f 6e 65 20 48 6f 6d 65 73 70 6f 74 01 08 82 84 8b 96 12 24 48 6c 03 01 0b 32 04 0c 18 30 60 07 2a 44 45 20 01 01 14 02 01 14 03 01 14 04 01 14 05 01 14 06 01 14 07 01 14 08 01 14 09 01 14 0a 01 14 0b 01 14 0c 01 14 0d 01 14 33 08 20 01 02 03 04 05 06 07 33 08 21 05 06 07 08 09 0a 0b 05 04 00 01 00 10 2a 01 00 2d 1a ee 11 17 ff ff ff 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 18 46 47 11 00 3d 16 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4a 0e 14 00 0a 00 2c 01 c8 00 14 00 05 00 19 00 7f 04 01 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 00 00 32 12 7a dd 07 00 0c 43 03 00 00 00 b6 f6 db 7b
17:05:20.577 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff 74 42 7f f0 ed 2a 74 42 7f f0 ed 2a a0 68 83 e1 03 9c 6a 01 00 00 64 00 31 14 00 05 45 42 34 30 42 01 08 82 84 8b 96 8c 12 98 24 03 01 0b 05 04 00 01 00 00 07 06 44 45 20 01 0d 14 2a 01 00 32 04 b0 48 60 6c 0b 05 00 00 10 00 00 46 05 73 d0 00 00 0c 2d 1a ad 09 03 ff ff 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00 00 3d 16 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4a 0e 14 00 0a 00 2c 01 c8 00 14 00 05 00 19 00 7f 08 05 00 0f 00 00 00 00 40 bf 0c b2 59 89 33 fa ff 00 00 fa ff 00 20 c0 05 00 00 00 fc ff c1 06 00 00 fa f1 00 00 dd 1a 00 90 4c 04 08 bf 0c b2 59 89 33 fa ff 00 00 fa ff 00 20 c0 05 00 00 00 fc ff dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 dd 09 00 03 7f 01 01 00 00 ff 7f dd 08 8c fd f0 01 01 02 01 00 dd 16 8c fd f0 04 00 00 49 4c 51 03 02 09 72 01 00 00 00 00 ef 12 00 00 dd 0c 00 04 0e 01 01 02 01 00 00 00 00 00 dd 1d 00 50 f2 04 10 4a 00 01 10 10 44 00 01 02 10 3c 00 01 03 10 49 00 06 00 37 2a 00 01 20 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00 57 61 8b dc
17:05:20.682 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff 90 5c 44 85 0a 7c 90 5c 44 85 0a 7c e0 65 6c 61 0c b3 12 00 00 00 64 00 31 04 00 1e 56 65 72 62 69 6e 64 75 6e 67 20 77 69 72 64 20 68 65 72 67 65 73 74 65 6c 6c 74 2e 2e 2e 01 08 82 84 8b 96 12 24 48 6c 03 01 0b 32 04 0c 18 30 60 07 2a 44 45 20 01 01 14 02 01 14 03 01 14 04 01 14 05 01 14 06 01 14 07 01 14 08 01 14 09 01 14 0a 01 14 0b 01 14 0c 01 14 0d 01 14 05 04 00 01 00 36 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00 2a 01 00 2d 1a ee 11 17 ff ff ff 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 18 46 47 11 00 3d 16 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4a 0e 14 00 0a 00 2c 01 c8 00 14 00 05 00 19 00 7f 04 01 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 00 00 32 12 7a dd 07 00 0c 43 03 00 00 00 8b 99 2b 24
...
17:05:24.346 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not process packet on probe [broad-monitor-wlx801f02eed6d7].
org.pcap4j.packet.IllegalRawDataException: rawData is too short. length field: 232, rawData: 40 00 00 00 ff ff ff ff ff ff 80 1f 02 e1 a9 33 ff ff ff ff ff ff 30 9a 00 00 01 08 82 84 8b 96 0c 12 18 24 32 04 30 48 60 6c 2d 1a 6e 18 1e ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 72 e8 e6 13, offset: 70, length: 4
        at org.pcap4j.packet.Dot11InformationElement.<init>(Dot11InformationElement.java:84) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.packet.Dot11MeshIdElement.<init>(Dot11MeshIdElement.java:65) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.packet.Dot11MeshIdElement.newInstance(Dot11MeshIdElement.java:54) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.packet.Dot11ProbeRequestPacket$Dot11ProbeRequestHeader.<init>(Dot11ProbeRequestPacket.java:586) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.packet.Dot11ProbeRequestPacket$Dot11ProbeRequestHeader.<init>(Dot11ProbeRequestPacket.java:458) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.packet.Dot11ProbeRequestPacket.newPacket(Dot11ProbeRequestPacket.java:45) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.parsers.Dot11ProbeRequestFrameParser.doParse(Dot11ProbeRequestFrameParser.java:44) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.parsers.Dot11ProbeRequestFrameParser.doParse(Dot11ProbeRequestFrameParser.java:32) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.parsers.Dot11FrameParser.parse(Dot11FrameParser.java:47) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.frames.Dot11FrameFactory.build(Dot11FrameFactory.java:59) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:196) ~[nzyme-1.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
17:05:24.693 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff 38 10 d5 22 f3 30 38 10 d5 22 f3 30 00 1c 80 d1 0e 9c 6a 01 00 00 64 00 31 14 00 05 40 48 6f 6d 65 01 08 82 84 8b 96 8c 12 98 24 03 01 04 05 04 00 01 00 00 07 06 44 45 20 01 0d 14 2a 01 00 32 04 b0 48 60 6c 46 05 73 d0 00 00 0c 2d 1a ad 01 1b ff ff ff 00 00 00 00 00 00 00 00 00 01 00 00 00 00 04 06 e6 07 0c 00 3d 16 04 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4a 0e 14 00 0a 00 2c 01 c8 00 14 00 05 00 19 00 7f 08 05 00 0f 00 00 00 00 40 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 dd 09 00 03 7f 01 01 00 00 ff 7f dd 08 8c fd f0 01 01 02 01 00 dd 16 8c fd f0 04 00 00 49 00 00 03 02 09 72 01 00 00 00 00 39 00 00 00 dd 0c 00 04 0e 01 01 02 01 00 00 00 00 00 dd 1d 00 50 f2 04 10 4a 00 01 10 10 44 00 01 02 10 3c 00 01 03 10 49 00 06 00 37 2a 00 01 20 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 80 00 d3 50 61 6c
...
17:05:26.818 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff fe ec da 1f f1 12 fe ec da 1f f1 12 50 f0 41 a0 6d 9a 6a 01 00 00 64 00 31 04 00 0c 6d 79 69 70 6e 67 5f 67 75 65 73 74 01 08 82 84 8b 96 12 24 48 6c 03 01 06 32 04 0c 18 30 60 05 04 00 03 00 20 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00 2a 01 00 2d 1a ac 01 17 ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3d 16 06 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 7f 08 01 00 00 00 00 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 04 00 18 12 7a dd 07 00 0c 43 03 00 00 00 dd 13 00 15 6d 00 01 01 00 01 02 20 ec 81 06 fc ec da 4f f1 11 49 c0 56 60
17:05:26.819 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff fe ec da 2f f1 12 fe ec da 2f f1 12 60 f0 56 a0 6d 9a 6a 01 00 00 64 00 31 04 00 00 01 08 82 84 8b 96 12 24 48 6c 03 01 06 32 04 0c 18 30 60 05 04 00 03 00 00 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00 2a 01 00 2d 1a ac 01 17 ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3d 16 06 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 7f 08 01 00 00 00 00 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 04 00 18 12 7a dd 07 00 0c 43 03 00 00 00 dd 16 00 15 6d 00 01 01 28 01 02 20 ec 81 06 fc ec da 4f f1 11 87 01 00 bf 3d d9 a4
17:05:26.821 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff fc ec da 4f 81 00 fc ec da 4f 81 00 d0 24 4f 10 3b 08 25 00 00 00 64 00 31 04 00 06 6d 79 69 70 6e 67 01 08 82 84 8b 96 12 24 48 6c 03 01 06 32 04 0c 18 30 60 05 05 02 03 00 a9 01 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00 2a 01 00 2d 1a ac 01 17 ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3d 16 06 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 7f 08 01 00 00 00 00 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 05 00 0b 12 7a dd 07 00 0c 43 03 00 00 00 dd 13 00 15 6d 00 01 01 00 01 02 20 ec 81 06 fc ec da 4f 80 ff 10 fc 53 21
17:05:26.823 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff fe ec da 1f 81 00 fe ec da 1f 81 00 e0 24 43 10 3b 08 25 00 00 00 64 00 31 04 00 0c 6d 79 69 70 6e 67 5f 67 75 65 73 74 01 08 82 84 8b 96 12 24 48 6c 03 01 06 32 04 0c 18 30 60 05 04 02 03 00 00 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00 2a 01 00 2d 1a ac 01 17 ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3d 16 06 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 7f 08 01 00 00 00 00 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 05 00 0b 12 7a dd 07 00 0c 43 03 00 00 00 dd 13 00 15 6d 00 01 01 00 01 02 20 ec 81 06 fc ec da 4f 80 ff 00 31 db 46
17:05:26.824 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff fe ec da 2f 81 00 fe ec da 2f 81 00 f0 24 46 10 3b 08 25 00 00 00 64 00 31 04 00 00 01 08 82 84 8b 96 12 24 48 6c 03 01 06 32 04 0c 18 30 60 05 04 02 03 00 00 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00 2a 01 00 2d 1a ac 01 17 ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3d 16 06 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 7f 08 01 00 00 00 00 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 05 00 0b 12 7a dd 07 00 0c 43 03 00 00 00 dd 16 00 15 6d 00 01 01 28 01 02 20 ec 81 06 fc ec da 4f 80 ff 87 01 00 4d d8 db cb
...

Startup:
17:07:01.331 [main] INFO  horse.wtf.nzyme.systemstatus.SystemStatus - Set system status [RUNNING].
17:07:01.332 [main] INFO  horse.wtf.nzyme.systemstatus.SystemStatus - Set system status [TRAINING].
17:07:05.712 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Training period ends in <300> seconds.
17:07:05.719 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Initializing nzyme version: 1.1.1 built at [2021-07-02T00:38:28Z].
17:07:05.721 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Active alerts: [UNEXPECTED_BSSID, UNEXPECTED_SSID, CRYPTO_CHANGE, UNEXPECTED_CHANNEL, BEACON_RATE_ANOMALY, MULTIPLE_SIGNAL_TRACKS, PWNAGOTCHI_ADVERTISEMENT, BANDIT_CONTACT]
17:07:05.722 [main] INFO  horse.wtf.nzyme.ouis.OUIManager - Fetching and updating list of OUIs from [http://standards-oui.ieee.org/oui/oui.txt]. This might take a moment.
17:07:21.081 [main] INFO  horse.wtf.nzyme.ouis.OUIManager - Done! Now <30605> OUIs in memory. Download time <1031ms>, parsing time <13s>.
17:07:21.143 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Registering uplink of type [horse.wtf.nzyme.notifications.uplinks.syslog.SyslogUDPRFC5424UDPUplink].
17:07:21.148 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [OUIUpdater] for every <12 HOURS> with <12 HOURS> initial delay.
17:07:21.149 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [MeasurementsWriter] for every <1 MINUTES> with <1 MINUTES> initial delay.
17:07:21.151 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [MeasurementsCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
17:07:21.153 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateWriter] for every <60 SECONDS> with <60 SECONDS> initial delay.
17:07:21.155 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
17:07:21.158 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalIndexHistogramWriter] for every <60 SECONDS> with <60 SECONDS> initial delay.
17:07:21.159 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalIndexHistogramCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
17:07:21.330 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [VersioncheckThread] for every <60 MINUTES> with <0 MINUTES> initial delay.
17:07:21.333 [periodicals-4] INFO  horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread - Starting to check for most recent nzyme version.
17:07:21.334 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateAnomalyAlertMonitor] for every <60 SECONDS> with <60 SECONDS> initial delay.
17:07:21.337 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalTrackMonitor] for every <60 SECONDS> with <60 SECONDS> initial delay.
17:07:22.322 [periodicals-4] INFO  horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread - Successfully completed version check. Everything seems up to date.
17:07:24.916 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Started web interface and REST API at [http://192.168.0.127:22900/]. Access it at: [http://192.168.0.127:22900/]
17:07:24.943 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Commencing 802.11 frame processing on [wlx801f02eed6d7] ... (⌐■_■)–︻╦╤─ – – pew pew
17:07:26.602 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlx801f02eed6d7]
17:07:27.308 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - PCAP handle for [broad-monitor-wlx801f02eed6d7] acquired. Cycling through channels <1,2,3,4,5,6,7,8,9,10,11>.
17:07:27.775 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff 90 5c 44 85 0a 7c 90 5c 44 85 0a 7c 30 4e 44 51 9c ba 12 00 00 00 64 00 31 04 00 1e 56 65 72 62 69 6e 64 75 6e 67 20 77 69 72 64 20 68 65 72 67 65 73 74 65 6c 6c 74 2e 2e 2e 01 08 82 84 8b 96 12 24 48 6c 03 01 0b 32 04 0c 18 30 60 07 2a 44 45 20 01 01 14 02 01 14 03 01 14 04 01 14 05 01 14 06 01 14 07 01 14 08 01 14 09 01 14 0a 01 14 0b 01 14 0c 01 14 0d 01 14 05 04 00 01 00 36 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00 2a 01 00 2d 1a ee 11 17 ff ff ff 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 18 46 47 11 00 3d 16 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4a 0e 14 00 0a 00 2c 01 c8 00 14 00 05 00 19 00 7f 04 01 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 00 00 2e 12 7a dd 07 00 0c 43 03 00 00 00 46 4a fa aa
17:07:27.809 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff 8a 5c 44 85 0a 7c 8a 5c 44 85 0a 7c 50 4e 08 64 9c ba 12 00 00 00 64 00 21 04 00 11 56 6f 64 61 66 6f 6e 65 20 48 6f 6d 65 73 70 6f 74 01 08 82 84 8b 96 12 24 48 6c 03 01 0b 32 04 0c 18 30 60 07 2a 44 45 20 01 01 14 02 01 14 03 01 14 04 01 14 05 01 14 06 01 14 07 01 14 08 01 14 09 01 14 0a 01 14 0b 01 14 0c 01 14 0d 01 14 33 08 20 01 02 03 04 05 06 07 33 08 21 05 06 07 08 09 0a 0b 05 04 00 01 00 10 2a 01 00 2d 1a ee 11 17 ff ff ff 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 18 46 47 11 00 3d 16 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4a 0e 14 00 0a 00 2c 01 c8 00 14 00 05 00 19 00 7f 04 01 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 00 00 2e 12 7a dd 07 00 0c 43 03 00 00 00 c0 8f 1f 50
17:07:27.839 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.Dot11TaggedParameters - Malformed 802.11 tagged parameters: 80 00 00 00 ff ff ff ff ff ff 86 5c 44 85 0a 7c 86 5c 44 85 0a 7c a0 4e e5 7a 9f ba 12 00 00 00 64 00 21 04 00 10 56 6f 64 61 66 6f 6e 65 20 48 6f 74 73 70 6f 74 01 08 82 84 8b 96 12 24 48 6c 03 01 0b 32 04 0c 18 30 60 07 2a 44 45 20 01 01 14 02 01 14 03 01 14 04 01 14 05 01 14 06 01 14 07 01 14 08 01 14 09 01 14 0a 01 14 0b 01 14 0c 01 14 0d 01 14 33 08 20 01 02 03 04 05 06 07 33 08 21 05 06 07 08 09 0a 0b 05 04 00 01 00 00 2a 01 00 2d 1a ee 11 17 ff ff ff 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 18 46 47 11 00 3d 16 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 4a 0e 14 00 0a 00 2c 01 c8 00 14 00 05 00 19 00 7f 04 01 00 00 00 dd 18 00 50 f2 02 01 01 00 00 03 a4 00 00 27 a4 00 00 42 43 5e 00 62 32 2f 00 0b 05 00 00 2e 12 7a dd 07 00 0c 43 03 00 00 00 34 34 78 3f


```

**Comment by lennartkoopmann** [comment]
Thank you! Would it be possible for you to send me a packet capture?

**Comment by crs369** [comment]
Sure - thanks for watching

[trace.pcap.gz](https://github.com/lennartkoopmann/nzyme/files/7122763/trace.pcap.gz)

**Comment by crs369** [comment]
Here is a new one with more packets - hope this helps. 

[trace.pcap.gz](https://github.com/lennartkoopmann/nzyme/files/7192056/trace.pcap.gz)

Did not seen differences in the Tagged Parameters for calculating the fingerprints at first, but i'm beeing wrong.

**Comment by lennartkoopmann** [comment]
This will be improved with the new v2.0.0 architecture.
