### ISSUE TITLE
Trying Alfa AWUS036ACS

### ISSUE THREAD

**Issue by crs369** [lennartkoopmann/nzyme#511]
Hello,

first my Environment:
Raspberry Pi 4 with 8 GB
WLAN-USB-Adapter Alfa AWUS036ACS

I want to setup nzyme with a USB-WLAN-Adapter with 2,5 und 5 GHz - my choice was a Alfa AWUS036ACS.

Baseimage is the actual rasbian - lite. After the installation WLAN-Driver from:

https://github.com/aircrack-ng/rtl8812au

i see that log Output:

```
21:30:11.518 [main] INFO  horse.wtf.nzyme.systemstatus.SystemStatus - Set system status [RUNNING].
21:30:11.524 [main] INFO  horse.wtf.nzyme.systemstatus.SystemStatus - Set system status [TRAINING].
21:30:11.549 [main] INFO  horse.wtf.nzyme.alerts.service.AlertsService - Registering alert callback of type [horse.wtf.nzyme.alerts.service.callbacks.EmailCallback].
21:30:15.653 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Training period ends in <300> seconds.
21:30:15.660 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Initializing nzyme version: 1.1.1 built at [2021-07-02T00:38:28Z].
21:30:15.662 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Active alerts: [UNEXPECTED_BSSID, UNEXPECTED_SSID, CRYPTO_CHANGE, UNEXPECTED_CHANNEL, UNEXPECTED_FINGERPRINT, BEACON_RATE_ANOMALY, MULTIPLE_SIGNAL_TRACKS, PWNAGOTCHI_ADVERTISEMENT, BANDIT_CONTACT]
21:30:15.663 [main] INFO  horse.wtf.nzyme.ouis.OUIManager - Fetching and updating list of OUIs from [http://standards-oui.ieee.org/oui/oui.txt]. This might take a moment.
21:30:31.280 [main] INFO  horse.wtf.nzyme.ouis.OUIManager - Done! Now <30574> OUIs in memory. Download time <981ms>, parsing time <14s>.
21:30:31.339 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Registering uplink of type [horse.wtf.nzyme.notifications.uplinks.syslog.SyslogUDPRFC5424UDPUplink].
21:30:31.343 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [OUIUpdater] for every <12 HOURS> with <12 HOURS> initial delay.
21:30:31.345 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [MeasurementsWriter] for every <1 MINUTES> with <1 MINUTES> initial delay.
21:30:31.346 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [MeasurementsCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
21:30:31.348 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateWriter] for every <60 SECONDS> with <60 SECONDS> initial delay.
21:30:31.351 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
21:30:31.353 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalIndexHistogramWriter] for every <60 SECONDS> with <60 SECONDS> initial delay.
21:30:31.356 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalIndexHistogramCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
21:30:31.462 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [VersioncheckThread] for every <60 MINUTES> with <0 MINUTES> initial delay.
21:30:31.464 [periodicals-4] INFO  horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread - Starting to check for most recent nzyme version.
21:30:31.465 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateAnomalyAlertMonitor] for every <60 SECONDS> with <60 SECONDS> initial delay.
21:30:31.468 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalTrackMonitor] for every <60 SECONDS> with <60 SECONDS> initial delay.
21:30:32.458 [periodicals-4] INFO  horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread - Successfully completed version check. Everything seems up to date.
21:30:34.719 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Started web interface and REST API at [http://192.168.0.127:22900/]. Access it at: [http://192.168.0.127:22900/]
21:30:34.747 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Commencing 802.11 frame processing on [wlx00c0caade606] ... (⌐■_■)–︻╦╤─ – – pew pew
21:30:35.941 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlx00c0caade606]
21:30:35.997 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlx00c0caade606]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: wlx00c0caade606: SIOCGIWPRIV: Argument list too long
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:45) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1529) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:116) ~[nzyme-1.1.1.jar:?]
        ... 6 more
21:30:39.547 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlx00c0caade606]
21:30:39.597 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlx00c0caade606]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: wlx00c0caade606: SIOCGIWPRIV: Argument list too long
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:45) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1529) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:116) ~[nzyme-1.1.1.jar:?]
        ... 6 more


```

Looking in the internet with "SIOCGIWPRIV: Argument list too long" i see two good links:
https://github.com/aircrack-ng/rtl8812au/issues/441
https://github.com/the-tcpdump-group/libpcap/issues/941

I'm trying to install the libpcap-dev and and the new Version of the OpenJDK

https://jamesachambers.com/upgrade-java-past-apts-openjdk-11-on-raspberry-pi-os/

No change at all. I Think the problem is in the pcap-library because tcpdump has the same problem:

pi@nzyme:/usr/share/nzyme/bin $ sudo /sbin/tcpdump -I -i wlx00c0caade606
tcpdump: wlx00c0caade606: SIOCGIWPRIV: Argument list too long

But i can't find the fix from the links above in the actual pcap.

Any tipps?

**Comment by lennartkoopmann** [comment]
Unfortunately, that adapter is known to not work very well. It's a common problem and I have a similar adapter just sitting here waiting for better driver support. I recommend using the adapters that are listed on the nzyme requirements page because they are known to work really well.

**Comment by crs369** [comment]
Sorry to bother you, but i give it another try.

I'm using the USB-Stick on the actual kali distribution and make the driver installation from

https://github.com/aircrack-ng/rtl8812au

Following this guide (not exactly);

https://kalitut.com/how-to-install-rtl8812au/

I can scan the wlan with 

`airodump-ng wlan0`

But nzyme says:
```

17:31:20.692 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Commencing 802.11 frame processing on [wlan0] ... (⌐■_■)–︻╦╤─ – – pew pew
17:31:20.950 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan0]
17:31:21.034 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlan0]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: That device doesn't support monitor mode
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:45) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1529) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:116) ~[nzyme-1.1.1.jar:?]
        ... 6 more

```


Can you upgrade Pcap4J or do something with the bindings to libpcap?
