### ISSUE TITLE
Armbian 21.08.2 Bullseye Could not initialize probe

### ISSUE THREAD

**Issue by MoHorst** [lennartkoopmann/nzyme#518]
Hello,
the TL-WN722N works fine with aircrack-ng on this orangepi plus 2e.

I already tried this.
setcap cap_net_raw,cap_net_admin=eip /usr/lib/jvm/java-11-openjdk-armhf/bin/java
setcap cap_net_raw,cap_net_admin=eip /usr/bin/python3.9

Interface is not manged by the NetworkManager
NetworkManager.conf
[main]
dns=default
rc-manager=file
plugins=ifupdown,keyfile
[keyfile]
unmanaged-devices=mac:f4:f2:xx:xx:xx:xx

[ifupdown]
managed=true

nzyme.log
`
[probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Commencing 802.11 frame processing on [wlxxxxxxx] ... (⌐■_■)–︻╦╤─ – – pew pew
 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlxxxxxxx]
[probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlxxxxxxx]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: That device doesn't support monitor mode
`

Any ideas?
Thanks
MoHorst

**Comment by MoHorst** [comment]
Just an update.
I tested two other WiFi dongles. Working fine with aircrack-ng, but the same issue in nzyme.

root@orangepiplus2e:~# lsusb | grep -v hub
Bus 005 Device 002: ID 2357:0115 TP-Link Archer T4U ver.3
Bus 004 Device 002: ID 0cf3:9271 Qualcomm Atheros Communications AR9271 802.11n
Bus 003 Device 002: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter

**Comment by lennartkoopmann** [comment]
Please try `skip_enable_monitor`: https://www.nzyme.org/docs/installation-configuration/configuration-reference#802_11_monitorsskip_enable_monitor

**Comment by MoHorst** [comment]
Sorry, no success.
It looks like, it doesn't skip the init task.  

  {
    #device: wlxxxxxxxxxxxx
    device: wlan2mon
    channels: [1,2,3,4,5,6,7,8,9]
    channel_hop_command: "sudo /sbin/iwconfig {interface} channel {channel}"
    channel_hop_interval: 1
    skip_enable_monitor: true
  }

root@orangepiplus2e:/var/log/nzyme# iwconfig wlan1mon
wlan1mon  IEEE 802.11  Mode:Monitor  Tx-Power=0 dBm
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Power Management:off


[probe-loop-2] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan1mon]
[probe-loop-2] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlan1mon]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.

**Comment by lennartkoopmann** [comment]
Please post the rest of the log, which will state the error that lead to the PCAP handle failure.

What nzyme version are you running?

**Comment by MoHorst** [comment]
Version: nzyme-1.1.1.jar

Interface:
PHY     Interface       Driver          Chipset

phy0    wlan0           rtl8189fs       unable to detect for sdio 0x024c:0xf179
phy1    wlan1mon        rt2800usb       Ralink Technology, Corp. RT5370
phy2    wlan2mon        ath9k_htc       Qualcomm Atheros Communications AR9271 802.11n
phy3    wlxd03745b865c9 rtl88x2bu       TP-Link Archer T4U ver.3
                (monitor mode enabled)



tail -f nzyme.log

08:30:36.879 [main] INFO  horse.wtf.nzyme.configuration.leader.LeaderConfigurationLoader - Skipping disabled alert callback of type [email].
08:30:49.756 [main] INFO  horse.wtf.nzyme.systemstatus.SystemStatus - Set system status [RUNNING].
08:30:49.757 [main] INFO  horse.wtf.nzyme.systemstatus.SystemStatus - Set system status [TRAINING].
08:31:00.994 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Training period ends in <300> seconds.
08:31:01.009 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Initializing nzyme version: 1.1.1 built at [2021-07-02T00:38:28Z].
08:31:01.012 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Active alerts: [UNEXPECTED_BSSID, UNEXPECTED_SSID, CRYPTO_CHANGE, UNEXPECTED_CHANNEL, UNEXPECTED_FINGERPRINT, BEACON_RATE_ANOMALY, MULTIPLE_SIGNAL_TRACKS, PWNAGOTCHI_ADVERTISEMENT, BANDIT_CONTACT]
08:31:01.014 [main] INFO  horse.wtf.nzyme.ouis.OUIManager - Fetching and updating list of OUIs from [http://standards-oui.ieee.org/oui/oui.txt]. This might take a moment.
08:31:12.847 [main] INFO  horse.wtf.nzyme.ouis.OUIManager - Done! Now <30695> OUIs in memory. Download time <692ms>, parsing time <10s>.
08:31:12.932 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [OUIUpdater] for every <12 HOURS> with <12 HOURS> initial delay.
08:31:12.935 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [MeasurementsWriter] for every <1 MINUTES> with <1 MINUTES> initial delay.
08:31:12.938 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [MeasurementsCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
08:31:12.941 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateWriter] for every <60 SECONDS> with <60 SECONDS> initial delay.
08:31:12.945 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
08:31:12.949 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalIndexHistogramWriter] for every <60 SECONDS> with <60 SECONDS> initial delay.
08:31:12.952 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalIndexHistogramCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
08:31:13.288 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [VersioncheckThread] for every <60 MINUTES> with <0 MINUTES> initial delay.
08:31:13.309 [periodicals-4] INFO  horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread - Starting to check for most recent nzyme version.
08:31:13.315 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateAnomalyAlertMonitor] for every <60 SECONDS> with <60 SECONDS> initial delay.
08:31:13.333 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalTrackMonitor] for every <60 SECONDS> with <60 SECONDS> initial delay.
08:31:14.720 [periodicals-4] INFO  horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread - Successfully completed version check. Everything seems up to date.
08:31:20.426 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Started web interface and REST API at [http://192.168.100.41:22900/]. Access it at: [http://192.168.100.41:22900/]
08:31:20.503 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Commencing 802.11 frame processing on [wlan2mon] ... (⌐■_■)–︻╦╤─ – – pew pew
08:31:20.516 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Commencing 802.11 frame processing on [wlxd03745b865c9] ... (⌐■_■)–︻╦╤─ – – pew pew
08:31:20.521 [probe-loop-2] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Commencing 802.11 frame processing on [wlan1mon] ... (⌐■_■)–︻╦╤─ – – pew pew
08:31:21.105 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan2mon]
08:31:21.268 [probe-loop-2] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan1mon]
08:31:21.259 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlan2mon]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: That device is not up
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:45) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1529) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:116) ~[nzyme-1.1.1.jar:?]
        ... 6 more
08:31:21.364 [probe-loop-1] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlxd03745b865c9]
08:31:21.366 [probe-loop-2] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlan1mon]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: That device is not up
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:45) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1529) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:116) ~[nzyme-1.1.1.jar:?]
        ... 6 more
08:31:21.407 [probe-loop-1] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlxd03745b865c9]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: Error occurred in pcap_compile: 802.11 link-layer types supported only on 802.11
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:482) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:508) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:117) ~[nzyme-1.1.1.jar:?]
        ... 6 more
08:31:23.868 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan2mon]
08:31:23.929 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlan2mon]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: That device is not up
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:45) ~[nzyme-1.1.1.jar:?]
        at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1529) ~[nzyme-1.1.1.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:116) ~[nzyme-1.1.1.jar:?]
        ... 6 more

**Comment by lennartkoopmann** [comment]
Is this still an issue? "Error occurred in pcap_compile: 802.11 link-layer types supported only on 802.11" sounds like the wrong network adapter is selected and libpcap believes this is not a WiFi adapter.
