### ISSUE TITLE
No PCAP handle: Argument list is too long

### ISSUE THREAD

**Issue by tzepter** [lennartkoopmann/nzyme#521]
My environment is Raspberry Pi 4 Model B Rev 1.2. iwconfig says:

`
wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=31 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          
wlxe848b88ef6f7  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.462 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

wlx28ee52198436  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
`
The wifi adapter config section looks like:

`
802_11_monitors: [
  {
    device: wlxe848b88ef6f7
    channels: [1,2,3,4,5,6]
    channel_hop_command: "sudo /sbin/iwconfig {interface} channel {channel}"
    channel_hop_interval: 1
    skip_enable_monitor: false
  }
  {
    device: wlx28ee52198436
    channels: [7,8,9,10,11]
    channel_hop_command: "sudo /sbin/iwconfig {interface} channel {channel}"
    channel_hop_interval: 1
    skip_enable_monitor: false
  }
]
`
The error messages (on both adapters are) are:
`
15:27:46.814 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlxe848b88ef6f7]
15:27:46.865 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlxe848b88ef6f7]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.1.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: wlxe848b88ef6f7: SIOCGIWPRIV: Die Argumentliste ist zu lang
	at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:166) ~[nzyme-1.1.1.jar:?]
	at org.pcap4j.core.PcapHandle.<init>(PcapHandle.java:45) ~[nzyme-1.1.1.jar:?]
	at org.pcap4j.core.PcapHandle$Builder.build(PcapHandle.java:1529) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:116) ~[nzyme-1.1.1.jar:?]
	... 6 more
`
The German phrase 'Die Argumentliste ist zu lang' stands for "the argument list is too long". The only suitable google hit I found was: https://github.com/mfontanini/libtins/issues/356 

Thx,
Tobi

**Comment by lennartkoopmann** [comment]
This is usually caused by an unsupported WiFi adapter.
