### ISSUE TITLE
Nzyme 1.1.1 - Mail-Alert not working

### ISSUE THREAD

**Issue by JohnDoeIsKIng** [lennartkoopmann/nzyme#522]
Hi community,
hi lennart,

the mail alert of the current version isn't working:
```
12:52:44.693 [probe-loop-0] INFO  horse.wtf.nzyme.alerts.service.AlertsService - Triggering alert callback type [horse.wtf.nzyme.alerts.service.callbacks.EmailCallback]
12:52:44.694 [probe-loop-0] INFO  horse.wtf.nzyme.alerts.service.callbacks.EmailCallback - Sending alert email.
12:52:55.650 [probe-loop-0] ERROR org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure - Failed to send email:
<902497.2.1631616765493@raspberrypi>
12:52:55.653 [probe-loop-0] ERROR horse.wtf.nzyme.alerts.service.callbacks.EmailCallback - Could not send Email.
org.simplejavamail.mailer.internal.MailerException: Third party error
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:87) ~[nzyme-1.1.1.jar:?]
	at org.simplejavamail.mailer.internal.AbstractProxyServerSyncingClosure.run(AbstractProxyServerSyncingClosure.java:56) ~[nzyme-1.1.1.jar:?]
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:345) ~[nzyme-1.1.1.jar:?]
	at org.simplejavamail.mailer.internal.MailerImpl.sendMail(MailerImpl.java:331) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.alerts.service.callbacks.EmailCallback.call(EmailCallback.java:92) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.alerts.service.AlertsService.handle(AlertsService.java:75) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.dot11.interceptors.UnexpectedFingerprintInterceptorSet$2.intercept(UnexpectedFingerprintInterceptorSet.java:91) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.dot11.interceptors.UnexpectedFingerprintInterceptorSet$2.intercept(UnexpectedFingerprintInterceptorSet.java:78) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.processing.FrameProcessor.processDot11Frame(FrameProcessor.java:64) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:196) ~[nzyme-1.1.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: javax.mail.MessagingException: Exception reading response
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2476) ~[nzyme-1.1.1.jar:?]
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2172) ~[nzyme-1.1.1.jar:?]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722) ~[nzyme-1.1.1.jar:?]
	at javax.mail.Service.connect(Service.java:364) ~[nzyme-1.1.1.jar:?]
	at javax.mail.Service.connect(Service.java:222) ~[nzyme-1.1.1.jar:?]
	at javax.mail.Service.connect(Service.java:171) ~[nzyme-1.1.1.jar:?]
	at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:75) ~[nzyme-1.1.1.jar:?]
	at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:48) ~[nzyme-1.1.1.jar:?]
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:78) ~[nzyme-1.1.1.jar:?]
	... 14 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:186) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:102) ~[nzyme-1.1.1.jar:?]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:271) ~[?:?]
	at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:100) ~[nzyme-1.1.1.jar:?]
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2456) ~[nzyme-1.1.1.jar:?]
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2172) ~[nzyme-1.1.1.jar:?]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722) ~[nzyme-1.1.1.jar:?]
	at javax.mail.Service.connect(Service.java:364) ~[nzyme-1.1.1.jar:?]
	at javax.mail.Service.connect(Service.java:222) ~[nzyme-1.1.1.jar:?]
	at javax.mail.Service.connect(Service.java:171) ~[nzyme-1.1.1.jar:?]
	at org.simplejavamail.mailer.internal.util.TransportRunner.runOnSessionTransport(TransportRunner.java:75) ~[nzyme-1.1.1.jar:?]
	at org.simplejavamail.mailer.internal.util.TransportRunner.sendMessage(TransportRunner.java:48) ~[nzyme-1.1.1.jar:?]
	at org.simplejavamail.mailer.internal.SendMailClosure.executeClosure(SendMailClosure.java:78) ~[nzyme-1.1.1.jar:?]
	... 14 more
```

Any hints what to do ?
Regards

JD.

**Comment by lennartkoopmann** [comment]
I've reformatted your log output to make it more readable. You can use ` ``` ` to format blocks of data and preserve indentation as well as newlines.

The error appears to be a network error: `Connection reset`. This means that nzyme was not able to connect to the configured SMTP server. (there was likely nothing listening on the other side)
