### ISSUE TITLE
Nzyme do not monitore same SSID

### ISSUE THREAD

**Issue by pponicki** [lennartkoopmann/nzyme#537]
Hello, I have four Access points, they all share the same SSID name. Nzyme allows me to monitore only one network from one AP. What can I do to monitore all four AP? At the bottom I put info from logs:

12:22:24.180 [main] ERROR horse.wtf.nzyme.Main - Invalid configuration. Please refer to the example configuration file or documentation.
horse.wtf.nzyme.configuration.InvalidConfigurationException: SSID [Here my SSID] is defined multiple times. You cannot define a network with the same SSID more than once.
	at horse.wtf.nzyme.configuration.BaseDot11ConfigurationLoader.validateNetworks(BaseDot11ConfigurationLoader.java:158) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.configuration.BaseDot11ConfigurationLoader.validate(BaseDot11ConfigurationLoader.java:114) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.configuration.leader.LeaderConfigurationLoader.validate(LeaderConfigurationLoader.java:427) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.configuration.leader.LeaderConfigurationLoader.<init>(LeaderConfigurationLoader.java:79) ~[nzyme-1.1.1.jar:?]
	at horse.wtf.nzyme.Main.main(Main.java:83) [nzyme-1.1.1.jar:?]

**Comment by lennartkoopmann** [comment]
Add multiple BSSIDs ("access point addresses") to the SSID like described in the documentation: https://www.nzyme.org/docs/installation-configuration/network-monitoring#bssids
