### ISSUE TITLE
Could not start nzyme

### ISSUE THREAD

**Issue by DroidKali** [lennartkoopmann/nzyme#776]
```
┌──(root㉿kali)-[~]
└─# /usr/bin/java -jar /usr/share/nzyme/nzyme.jar -c /etc/nzyme/nzyme.conf 

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
14:40:16.930 [main] INFO  horse.wtf.nzyme.configuration.leader.LeaderConfigurationLoader - Skipping disabled alert callback of type [email].
14:40:16.938 [main] INFO  horse.wtf.nzyme.configuration.leader.LeaderConfigurationLoader - Skipping disabled alert callback of type [file].
2月 10, 2023 2:40:19 下午 liquibase.lockservice
信息: Successfully acquired change log lock
2月 10, 2023 2:40:19 下午 liquibase.servicelocator
信息: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.json.JsonChangeLogParser Unable to get public no-arg constructor
2月 10, 2023 2:40:19 下午 liquibase.servicelocator
信息: Cannot load service: liquibase.parser.ChangeLogParser: liquibase.parser.core.yaml.YamlChangeLogParser Unable to get public no-arg constructor
2月 10, 2023 2:40:20 下午 liquibase.changelog
信息: Reading from public.databasechangelog
2月 10, 2023 2:40:21 下午 liquibase.servicelocator
信息: Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2月 10, 2023 2:40:21 下午 liquibase.lockservice
信息: Successfully released change log lock
14:40:21.615 [main] INFO  horse.wtf.nzyme.dot11.networks.sentry.Sentry - Loading <0> SSIDs from database into sentry table.
14:40:22.229 [main] INFO  horse.wtf.nzyme.systemstatus.SystemStatus - Set system status [RUNNING].
14:40:22.230 [main] INFO  horse.wtf.nzyme.systemstatus.SystemStatus - Set system status [TRAINING].
14:40:25.204 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Training period ends in <300> seconds.
14:40:25.210 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Initializing nzyme version: 1.2.2 built at [2021-12-10T15:28:11Z].
14:40:25.314 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Active alerts: [UNEXPECTED_BSSID, UNEXPECTED_SSID, CRYPTO_CHANGE, UNEXPECTED_CHANNEL, UNEXPECTED_FINGERPRINT, BEACON_RATE_ANOMALY, MULTIPLE_SIGNAL_TRACKS, PWNAGOTCHI_ADVERTISEMENT, BANDIT_CONTACT, UNKNOWN_SSID, DEAUTH_FLOOD]
14:40:25.315 [main] INFO  horse.wtf.nzyme.ouis.OUIManager - Fetching and updating list of OUIs from [http://standards-oui.ieee.org/oui/oui.txt]. This might take a moment.
14:41:06.258 [main] INFO  horse.wtf.nzyme.ouis.OUIManager - Done! Now <33297> OUIs in memory. Download time <16924ms>, parsing time <23s>.
14:41:06.688 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [OUIUpdater] for every <12 HOURS> with <12 HOURS> initial delay.
14:41:06.705 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [MeasurementsWriter] for every <1 MINUTES> with <1 MINUTES> initial delay.
14:41:06.725 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [MeasurementsCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
14:41:06.737 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateWriter] for every <60 SECONDS> with <60 SECONDS> initial delay.
14:41:06.780 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
14:41:06.809 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalIndexHistogramWriter] for every <60 SECONDS> with <60 SECONDS> initial delay.
14:41:06.813 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalIndexHistogramCleaner] for every <10 MINUTES> with <0 MINUTES> initial delay.
14:41:06.826 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [ProbeStatusMonitor] for every <1 MINUTES> with <1 MINUTES> initial delay.
14:41:07.051 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [VersioncheckThread] for every <60 MINUTES> with <0 MINUTES> initial delay.
14:41:07.054 [periodicals-4] INFO  horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread - Starting to check for most recent nzyme version.
14:41:07.059 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [BeaconRateAnomalyAlertMonitor] for every <60 SECONDS> with <60 SECONDS> initial delay.
14:41:07.065 [main] INFO  horse.wtf.nzyme.periodicals.PeriodicalManager - Scheduling [SignalTrackMonitor] for every <60 SECONDS> with <60 SECONDS> initial delay.
14:41:09.857 [main] INFO  horse.wtf.nzyme.NzymeLeaderImpl - Started web interface and REST API at [http://127.0.0.1:22900/]. Access it at: [http://127.0.0.1:22900/]
14:41:09.903 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Commencing 802.11 frame processing on [wlan0] ... (⌐■_■)–︻╦╤─ – – pew pew
14:41:10.391 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan0]
14:41:10.443 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlan0]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: Error occurred in pcap_compile: 802.11 link-layer types supported only on 802.11
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:482) ~[nzyme-1.2.2.jar:?]
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:508) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:117) ~[nzyme-1.2.2.jar:?]
        ... 6 more
14:41:10.914 [periodicals-4] INFO  horse.wtf.nzyme.periodicals.versioncheck.VersioncheckThread - Successfully completed version check. Everything seems up to date.
14:41:13.004 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan0]
14:41:13.029 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlan0]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: Error occurred in pcap_compile: 802.11 link-layer types supported only on 802.11
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:482) ~[nzyme-1.2.2.jar:?]
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:508) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:117) ~[nzyme-1.2.2.jar:?]
        ... 6 more
14:41:15.584 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan0]
14:41:15.620 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlan0]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: Error occurred in pcap_compile: 802.11 link-layer types supported only on 802.11
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:482) ~[nzyme-1.2.2.jar:?]
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:508) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:117) ~[nzyme-1.2.2.jar:?]
        ... 6 more
14:41:18.170 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan0]
14:41:18.199 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlan0]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.pcap4j.core.PcapNativeException: Error occurred in pcap_compile: 802.11 link-layer types supported only on 802.11
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:482) ~[nzyme-1.2.2.jar:?]
        at org.pcap4j.core.PcapHandle.setFilter(PcapHandle.java:508) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:117) ~[nzyme-1.2.2.jar:?]
        ... 6 more
14:41:20.714 [probe-loop-0] INFO  horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Building PCAP handle on interface [wlan0]
14:41:20.742 [probe-loop-0] ERROR horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe - Could not initialize probe [broad-monitor-wlan0]. Retrying soon.
horse.wtf.nzyme.dot11.probes.Dot11ProbeInitializationException: Could not build PCAP handle.
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.initialize(Dot11MonitorProbe.java:122) ~[nzyme-1.2.2.jar:?]
        at horse.wtf.nzyme.dot11.probes.Dot11MonitorProbe.lambda$loop$0(Dot11MonitorProbe.java:136) ~[nzyme-1.2.2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by DroidKali** [comment]
Solved by running:
```
sudo airmon-ng check kill
```
